### ISSUE TITLE
Failed to load recommendations

### ISSUE THREAD

**Issue by rumly111** [shhossain/novelupdates-extension#1]
The extension doesn't work. Under "Recommendations (AI)" it says "Loading..." and then "Failed to load recommendations". I tried in Chrome and FF

**Comment by shhossain** [comment]
@rumly111 check now.

**Comment by rumly111** [comment]
it works now in FF (probably in Chrome too, didn't check)
Hey, the addon was updated in FF store March 27, but your latest commit on github was 4 moths ago. You don't publish the source code anymore?

**Comment by rumly111** [comment]
fxd
